### ISSUE TITLE
Stackdump during DB write

### ISSUE THREAD

**Issue by Ness199X** [HearthSim/stove#32]
Seems to happen on all DB writes, including database migration (-migrate), creating a new deck, etc. Writes a db-journal file into the db directory that, if not deleted, causes Stove to stackdump on startup. Example dump below.
(Tested on 160202-kettle branch,. revision 85b455f)
```
Exception 0xc0000005 0x8 0xd6f140 0xd6f140
PC=0xd6f140
signal arrived during cgo execution

github.com/mattn/go-sqlite3._Cfunc__sqlite3_exec(0x3379e8, 0x121f240, 0xc0820d7470, 0xc0820d7478, 0xc000000000)
	github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:119 +0x4a
github.com/mattn/go-sqlite3.(*SQLiteConn).exec(0xc0820f1c20, 0xc082154b40, 0x93, 0x0, 0x0, 0x0, 0x0)
	F:/Hearthsim/src/github.com/mattn/go-sqlite3/sqlite3.go:581 +0xd8
github.com/mattn/go-sqlite3.(*SQLiteConn).Exec(0xc0820f1c20, 0xc082154b40, 0x93, 0xda2f28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	F:/Hearthsim/src/github.com/mattn/go-sqlite3/sqlite3.go:518 +0x92
database/sql.(*DB).exec(0xc0820e25a0, 0xc082154b40, 0x93, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/database/sql/sql.go:898 +0x2e9
database/sql.(*DB).Exec(0xc0820e25a0, 0xc082154b40, 0x93, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/database/sql/sql.go:875 +0xd4
github.com/jinzhu/gorm.(*Scope).Exec(0xc082120d00, 0x0)
	F:/Hearthsim/src/github.com/jinzhu/gorm/scope.go:322 +0x11a
github.com/jinzhu/gorm.(*Scope).createTable(0xc082120d00, 0xc082120d00)
	F:/Hearthsim/src/github.com/jinzhu/gorm/scope_private.go:571 +0x8fe
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc082120d00, 0xc082120d00)
	F:/Hearthsim/src/github.com/jinzhu/gorm/scope_private.go:631 +0xfc
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xd95fc0, 0xc0820d7d50, 0x10, 0x10, 0xda2f28)
	F:/Hearthsim/src/github.com/jinzhu/gorm/main.go:419 +0xd1
github.com/HearthSim/stove/pegasus.Migrate()
	F:/Hearthsim/src/github.com/HearthSim/stove/pegasus/db.go:55 +0x787
main.main()
	F:/HearthSim/stove/stove.go:23 +0x240

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0820e21e0)
	c:/go/src/database/sql/sql.go:589 +0x53
created by database/sql.Open
	c:/go/src/database/sql/sql.go:452 +0x323

goroutine 7 [IO wait]:
net.(*pollDesc).Wait(0xc08210a170, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08204e618, 0xc08210a060, 0xa67ef0, 0x8, 0xc082125db0, 0xc08210a180, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).acceptOne(0xc08210a000, 0xc0820508c0, 0x2, 0x2, 0xc08210a060, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:558 +0x547
net.(*netFD).accept(0xc08210a000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:585 +0x17a
net.(*TCPListener).AcceptTCP(0xc08204e628, 0x0, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:234 +0x55
net.(*TCPListener).Accept(0xc08204e628, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:244 +0x53
github.com/HearthSim/stove/pegasus/game.(*server).serve(0xc08205b920)
	F:/Hearthsim/src/github.com/HearthSim/stove/pegasus/game/server.go:32 +0x57
created by github.com/HearthSim/stove/pegasus/game.NewServer
	F:/Hearthsim/src/github.com/HearthSim/stove/pegasus/game/server.go:26 +0x2d7

goroutine 8 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0820e25a0)
	c:/go/src/database/sql/sql.go:589 +0x53
created by database/sql.Open
	c:/go/src/database/sql/sql.go:452 +0x323
rax     0x0
rbx     0x3
rcx     0xf0
rdx     0xbc16e0
rdi     0x0
rsi     0x1219cd8
rbp     0x1
rsp     0x22f798
r8      0x1
r9      0x1219bc0
r10     0x0
r11     0x207
r12     0x0
r13     0x1
r14     0x3
r15     0x2
rip     0xd6f140
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
exit status 2
```

**Comment by djkaty** [comment]
Try with the latest version of stove, I can't reproduce this now.

**Comment by Ness199X** [comment]
I posted this months ago, I later found out it was caused by my having an extremely out of date version of gorm. Closing.
