### ISSUE TITLE
Can't install "unable to open database" and "no such table: deck_card" + "no such table: account"

### ISSUE THREAD

**Issue by Retalyx** [HearthSim/Stove#84]
Hi, i got many error when running install on Windows 10, i done all previous installation steps from the wiki but always getting these errors :

```
C:\Go\work\src\github.com\HearthSim\stove>install
Fetching data files from http://github.com/HearthSim/hs-data.git
Creating database in "C:\Go\work\src\github.com\HearthSim\stove\db\pegasus.db"
INSERT INTO dbf_achieve VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_adventure VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_adventure_data VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_adventure_mission VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_banner VALUES (?, ?, ?, ?)
INSERT INTO dbf_board VALUES (?, ?, ?)
INSERT INTO dbf_booster VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_card_back VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_card VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_fixed_reward VALUES (?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_fixed_reward_action VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_fixed_reward_map VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_hero VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_scenario VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_season VALUES (?, ?, ?, ?)
INSERT INTO dbf_wing VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Creating pegasus tables
panic: unable to open database file

goroutine 1 [running]:
panic(0x941c60, 0xc042131ac0)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/HearthSim/stove/bnet.openDB(0x472573)
        C:/Go/work/src/github.com/HearthSim/stove/bnet/db.go:20 +0x258
github.com/HearthSim/stove/bnet.init()
        C:/Go/work/src/github.com/HearthSim/stove/bnet/db.go:11 +0x109
main.init()
        C:/Go/work/src/github.com/HearthSim/stove/stove.go:47 +0x3a
exit status 2
Initializing database
Traceback (most recent call last):
  File "C:\Go\work\src\github.com\HearthSim\stove\scripts\initialize_database.py", line 337, in <module>
    main()
  File "C:\Go\work\src\github.com\HearthSim\stove\scripts\initialize_database.py", line 221, in main
    connection.execute("DELETE FROM deck_card WHERE deck_id IN (SELECT id FROM deck WHERE deck_type = ?)", (deck_type,))
sqlite3.OperationalError: no such table: deck_card
Creating default user
Traceback (most recent call last):
  File "C:\Go\work\src\github.com\HearthSim\stove\scripts\create_user.py", line 203, in <module>
    main()
  File "C:\Go\work\src\github.com\HearthSim\stove\scripts\create_user.py", line 38, in main
    cursor_bnet.execute("SELECT COUNT(*) FROM account WHERE email = ?", (email,))
sqlite3.OperationalError: no such table: account
Done.
```

**Comment by djkaty** [comment]
Do you have a file in stove\db called bnet.db?

**Comment by Retalyx** [comment]
Yes but, it's empty

**Comment by djkaty** [comment]
Could you run the following commands from the stove folder and paste the output?

set BNET_DB=db\bnet.db
go run stove.go -migrate

**Comment by Retalyx** [comment]
Of course :) There is the output

```
C:\Go\work\src\github.com\HearthSim\stove>go run stove.go -migrate
panic: unable to open database file

goroutine 1 [running]:
panic(0x941c60, 0xc04217e540)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/HearthSim/stove/pegasus.openDB(0xc042123170)
        C:/Go/work/src/github.com/HearthSim/stove/pegasus/db.go:20 +0x254
github.com/HearthSim/stove/pegasus.init()
        C:/Go/work/src/github.com/HearthSim/stove/pegasus/db.go:11 +0xa5
main.init()
        C:/Go/work/src/github.com/HearthSim/stove/stove.go:47 +0x44
exit status 2
```

**Comment by Retalyx** [comment]
For information, pegasus.db has a size of 684 032 octets and bnet.db a size of 0 octets

**Comment by djkaty** [comment]
I'm unable to re-produce the bug, I just tried now on a fresh install.

Do you have sqlite3 installed for the version of Python you are using, and is the correct version (matching your Python install) being loaded when you run the go script?

**Comment by Retalyx** [comment]
I have the version 2.6.0, what version do you have?

```
C:\Go\work\src\github.com\HearthSim\stove>python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.version
'2.6.0'
```

**Comment by djkaty** [comment]
Exactly the same. That is really bizarre. And you only have one copy of Python installed?

**Comment by Retalyx** [comment]
Yes, i removed all other version installed to fix a problem with pip yesterday, so now, i only have python 3.5.1 installed

**Comment by Retalyx** [comment]
But when i search the code, i don't see any line creating tables "account" or "deck_card", is this normal?

**Comment by djkaty** [comment]
Okay, let's check the path
On line 18 of bnet\db.go, insert the following line:

println(dbFile)

Then save, set BNET_DB and run go run stove.go -migrate again

Does it print the correct path? (....\db\bnet.db)

**Comment by djkaty** [comment]
Yes it's normal, migrate should see that the database is empty then add all missing tables

**Comment by Retalyx** [comment]
Ok i'll test that, i'll restart from "install" command

There is output : 

```
C:\Go\work\src\github.com\HearthSim\stove>set PEGASUS_DB="%CD%\db\pegasus.db"

C:\Go\work\src\github.com\HearthSim\stove>set BNET_DB="%CD%\db\bnet.db"

C:\Go\work\src\github.com\HearthSim\stove>install
Fetching data files from http://github.com/HearthSim/hs-data.git
Creating database in "C:\Go\work\src\github.com\HearthSim\stove\db\pegasus.db"
INSERT INTO dbf_achieve VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_adventure VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_adventure_data VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_adventure_mission VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_banner VALUES (?, ?, ?, ?)
INSERT INTO dbf_board VALUES (?, ?, ?)
INSERT INTO dbf_booster VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_card_back VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_card VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_fixed_reward VALUES (?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_fixed_reward_action VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_fixed_reward_map VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_hero VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_scenario VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO dbf_season VALUES (?, ?, ?, ?)
INSERT INTO dbf_wing VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Creating pegasus tables
"C:\Go\work\src\github.com\HearthSim\stove\db\bnet.db"
panic: unable to open database file

goroutine 1 [running]:
panic(0x941cc0, 0xc04214d820)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/HearthSim/stove/bnet.openDB(0x472573)
        C:/Go/work/src/github.com/HearthSim/stove/bnet/db.go:21 +0x2a8
github.com/HearthSim/stove/bnet.init()
        C:/Go/work/src/github.com/HearthSim/stove/bnet/db.go:11 +0x109
main.init()
        C:/Go/work/src/github.com/HearthSim/stove/stove.go:47 +0x3a
exit status 2
Initializing database
Traceback (most recent call last):
  File "C:\Go\work\src\github.com\HearthSim\stove\scripts\initialize_database.py", line 337, in <module>
    main()
  File "C:\Go\work\src\github.com\HearthSim\stove\scripts\initialize_database.py", line 221, in main
    connection.execute("DELETE FROM deck_card WHERE deck_id IN (SELECT id FROM deck WHERE deck_type = ?)", (deck_type,))
sqlite3.OperationalError: no such table: deck_card
Creating default user
Traceback (most recent call last):
  File "C:\Go\work\src\github.com\HearthSim\stove\scripts\create_user.py", line 203, in <module>
    main()
  File "C:\Go\work\src\github.com\HearthSim\stove\scripts\create_user.py", line 38, in main
    cursor_bnet.execute("SELECT COUNT(*) FROM account WHERE email = ?", (email,))
sqlite3.OperationalError: no such table: account
Done.

C:\Go\work\src\github.com\HearthSim\stove>go run stove.go -migrate
"C:\Go\work\src\github.com\HearthSim\stove\db\bnet.db"
panic: unable to open database file

goroutine 1 [running]:
panic(0x941cc0, 0xc04214f840)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/HearthSim/stove/bnet.openDB(0x472573)
        C:/Go/work/src/github.com/HearthSim/stove/bnet/db.go:21 +0x2a8
github.com/HearthSim/stove/bnet.init()
        C:/Go/work/src/github.com/HearthSim/stove/bnet/db.go:11 +0x109
main.init()
        C:/Go/work/src/github.com/HearthSim/stove/stove.go:47 +0x3a
exit status 2
```

Your println output is `"C:\Go\work\src\github.com\HearthSim\stove\db\bnet.db"` wich is the right path

**Comment by djkaty** [comment]
There should be no quotes around the path. Did you clone the latest version of stove? Can you paste the install.bat file please? :)

**Comment by Retalyx** [comment]
Yes i should have the latest one :)

install.bat
```
@echo off

set BASEDIR=%CD%
set DATADIR=%BASEDIR%\hs-data
set HSDATA=http://github.com/HearthSim/hs-data.git

mkdir "%BASEDIR%\db" >nul 2>&1

if "%PEGASUS_DB%" == "" (
	echo PEGASUS_DB is not defined, using default location %BASEDIR%\db\pegasus.db
	set PEGASUS_DB=%BASEDIR%\db\pegasus.db
)

if exist "%PEGASUS_DB%" (
	if "%~1"=="" (
		echo %PEGASUS_DB% already exists.  If you want to rerun the bootstrapper, remove it.
		exit /B 1
	)
	if "%~1"=="-f" (
		echo %PEGASUS_DB% already exists - removing.
		del %PEGASUS_DB%
	)
)

if "%BNET_DB%" == "" (
	echo BNET_DB is not defined, using default location %BASEDIR%\db\bnet.db
	set BNET_DB=%BASEDIR%\db\bnet.db
)

if exist "%BNET_DB%" (
	if "%~1"=="" (
		echo %BNET_DB% already exists.  If you want to rerun the bootstrapper, remove it.
		exit /B 1
	)
	if "%~1"=="-f" (
		echo %BNET_DB% already exists - removing.
		del %BNET_DB%
	)
)

echo Fetching data files from %HSDATA%

if exist "%DATADIR%" (
	rmdir /S /Q "%DATADIR%"
)
git clone --depth=1 "%HSDATA%" "%DATADIR%" >nul 2>&1

echo Creating database in %PEGASUS_DB%
python "%BASEDIR%\scripts\dbf_to_sqlite.py" "%DATADIR%" "%PEGASUS_DB%"

echo Creating pegasus tables
go run "%BASEDIR%\stove.go" -migrate

echo Initializing database
python "%BASEDIR%\scripts\initialize_database.py" "%PEGASUS_DB%"

echo Creating default user
python "%BASEDIR%\scripts\create_user.py" "%PEGASUS_DB%" "%BNET_DB%" Test#1234 0123456789abcdef0123456789abcdef "test@hearthsim.info" "HearthSim Test User"

echo Done.
```

**Comment by djkaty** [comment]
The quotes are the problem. The question is why you are getting quotes. See this:

```
C:\Go\work\src\github.com\HearthSim\stove>set BNET_DB="db\bnet.db"

C:\Go\work\src\github.com\HearthSim\stove>echo %BNET_DB%
"db\bnet.db"

C:\Go\work\src\github.com\HearthSim\stove>go run stove.go -migrate
"db\bnet.db"
panic: unable to open database file

goroutine 1 [running]:
panic(0xaf17a0, 0xc08211f9c0)
        C:/Go/src/runtime/panic.go:464 +0x3f4
github.com/HearthSim/stove/bnet.openDB(0xc08200a250)
        C:/Go/Work/src/github.com/HearthSim/stove/bnet/db.go:21 +0x1ed
github.com/HearthSim/stove/bnet.init()
        C:/Go/Work/src/github.com/HearthSim/stove/bnet/db.go:11 +0x10c
main.init()
        C:/Go/work/src/github.com/HearthSim/stove/stove.go:46 +0x47
exit status 2

C:\Go\work\src\github.com\HearthSim\stove>set BNET_DB=db\bnet.db

C:\Go\work\src\github.com\HearthSim\stove>echo %BNET_DB%
db\bnet.db

C:\Go\work\src\github.com\HearthSim\stove>go run stove.go -migrate
db\bnet.db

[35m(no such table: dbf_card)[0m
[33m[2016-09-05 19:30:36][0m [31;1m [0m
Performing database migration
```

In the first attempt, where BNET_DB is quoted, the migration fails. In the second attempt, with no quotes, it succeeds.

I wonder if there is something in your environment settings that would cause it to be quoted?

You can try:

set BNET_DB=db\bnet.db
echo %BNET_DB%

There should be no quotes. If there are quotes, there is a setting in your environment affecting the way variables are set. In which case, I need to modify the install script to override it, so we need to find out how :)

**Comment by Retalyx** [comment]
Good, it worked, i had to rmove quotes in set=**** commands :) thanks you
You should probably fix this in the wiki

> Complete stove installation
> 
> cd %GOPATH%\src\github.com\HearthSim
> git clone http://github.com/HearthSim/stove
> cd stove
> set PEGASUS_DB="%CD%\db\pegasus.db"
> set BNET_DB="%CD%\db\bnet.db"
> install

While you'r there, i have another little question about a step from the wiki

**Comment by djkaty** [comment]
ahhhhhh the problem was in the wiki! Actually setting the DB values is unnecessary now, so I can just remove that altogether and make installation easier.

But, did you accidentally add quotes earlier when I asked you to do this?
set BNET_DB=db\bnet.db
go run stove.go -migrate

You pasted a log of it failing?

Please go ahead with your other question :)

**Comment by Retalyx** [comment]
Yes thes was a mistake x) but thanks again :)

My other question is :
I don't really understand this step :

Hearthstone Client

> - Grab and build UnityHook in Visual Studio (the free Community Edition is good enough). Details for doing this are in the UnityHook README. Place Assembly-CSharp.dll and Assembly-CSharp-firstpass.dll in UnityHook's lib folder before building. These files can be found in HS_DIR\Hearthstone_Data\Managed.
> - Run UnityHook on the Hearthstone install.
> - Write the client.config text (see below) to HS_DIR\client.config.

And this step in particular 
> - Run UnityHook on the Hearthstone install.

**Comment by djkaty** [comment]
I believe you can just build UnityHook and type 'bootstrap' from the project folder to run it. You may need to edit the path in bootstrap.bat to match your Hearthstone path!

**Comment by djkaty** [comment]
but actually, there is an easier way now, I made a project called HearthSwitcher which you can use to switch between stove and the official servers very easily, so perhaps just download that. You must build it in Debug mode to get the Developer tab :)

**Comment by Retalyx** [comment]
Thanks, i'll try this and keep you informed if i have any problem or question :) thanks again :)

**Comment by djkaty** [comment]
No problem, I'm the lead for Stove, Kettle, UnityHook, DeepLog and HearthSwitcher (they offloaded all the messy server stuff onto me :P) so just pop in IRC (KatyHearthstone) if you need any help!

**Comment by djkaty** [comment]
Oh... chat.freenode.net channel #hearthsim :) Closing this issue now.

I have fixed the wiki, thank you.
