### ISSUE TITLE
Unable to connect to Stove

### ISSUE THREAD

**Issue by tzurbaev** [HearthSim/Stove#87]
Greetings,

I'm trying to connect to Stove with current game client but I can't. My installation process was like:

- I've followed all steps from Wiki (Windows installation);
- Compiled UnityHook (with Assembly-CSharp.dll and Assembly-CSharp-firstpass.dll in **lib** directory);
- Added BattleNetCSharp.Init to example_hooks
- Executed `Hooker path/to/Hearthstone_Data example_hooks`
- Cloned fireplace (this may be wrong: copied `kettle/kettle.py` to fireplace's root dir, ran `python kettle.py`, kettle is listening now);
- `go run stove.go` (server is listening on 1119)

At first time client was stuck on loading screen; Stove log: `"server.go:169: handling packet service_id:0 method_id:5 token:41 size:0"`, token value keeps incrementing.

I've tried several times but no luck. After retries Stove starts crashing with 
```
2016/10/13 17:28:11 auth.go:135: account test@hearthsim.info (BattleTag: Test#1234) authorized
2016/10/13 17:28:11 session.go:172: session error: runtime error: invalid memory address or nil pointer dereference
=== STACK TRACE ===
goroutine 22 [running]:
runtime/debug.Stack(0xc042081608, 0x8e1c40, 0xc04200a0b0)
	C:/Go/src/runtime/debug/stack.go:24 +0x80
github.com/HearthSim/stove/bnet.(*Session).DisconnectOnPanic(0xc04206e240)

	J:/Go/src/github.com/HearthSim/stove/bnet/session.go:172 +0x75
panic(0x8e1c40, 0xc04200a0b0)

	C:/Go/src/runtime/panic.go:458 +0x251
github.com/HearthSim/stove/pegasus.(*Account).Init(0xc0423c2028, 0xc0423c2000)

	J:/Go/src/github.com/HearthSim/stove/pegasus/account.go:12 +0x71
github.com/HearthSim/stove/pegasus.BindSession(0xc0424de1a0, 0xc04206e240)

	J:/Go/src/github.com/HearthSim/stove/pegasus/session.go:37 +0xf1
github.com/HearthSim/stove/pegasus.(*Server).Connect(0xc0424de1a0, 0xc04206e240)

	J:/Go/src/github.com/HearthSim/stove/pegasus/server.go:17 +0x3c
github.com/HearthSim/stove/bnet.(*Server).ConnectGameServer(0xc04227e120, 0xc04206e240, 0xc042466ec0, 0x4)

	J:/Go/src/github.com/HearthSim/stove/bnet/server.go:113 +0x83
github.com/HearthSim/stove/bnet.(*AuthServerService).CompleteLogin(0xc04242a900, 0x25, 0xc042081bc0)

	J:/Go/src/github.com/HearthSim/stove/bnet/auth.go:174 +0x614
github.com/HearthSim/stove/bnet.(*AuthServerService).VerifyWebCredentials(0xc04242a900, 0xc042396000, 0x38, 0x1000, 0xd48c40, 0xc521ca)

	J:/Go/src/github.com/HearthSim/stove/bnet/auth.go:139 +0x433
github.com/HearthSim/stove/bnet.(*AuthServerService).Invoke(0xc04242a900, 0x7, 0xc042396000, 0x38, 0x1000, 0x0, 0xce, 0x0, 0x0, 0x1c)

	J:/Go/src/github.com/HearthSim/stove/bnet/auth.go:66 +0x43a
github.com/HearthSim/stove/bnet.(*Session).HandleRequest(0xc04206e240, 0x1, 0x7, 0xc042396000, 0x38, 0x1000, 0xd48c40, 0xc52200, 0xc0421e8000)

	J:/Go/src/github.com/HearthSim/stove/bnet/session.go:262 +0x254
github.com/HearthSim/stove/bnet.(*Session).HandlePacket(0xc04206e240, 0xc04211f420, 0xc042396000, 0x38, 0x1000)

	J:/Go/src/github.com/HearthSim/stove/bnet/session.go:212 +0x13f
github.com/HearthSim/stove/bnet.(*Server).handleClient(0xc04227e120, 0xd04640, 0xc0424de1b8)

	J:/Go/src/github.com/HearthSim/stove/bnet/server.go:170 +0x55a
created by github.com/HearthSim/stove/bnet.(*Server).ListenAndServe

	J:/Go/src/github.com/HearthSim/stove/bnet/server.go:107 +0xc7

2016/10/13 17:28:11 session.go:173: closing session
2016/10/13 17:28:12 channel_subscriber.go:77: ChannelSubscriberService closing down for connection
```

Some issues I ran into while compiling/running hooker:

1. VS reported `Error CS1501 No overload for method 'Init' takes 6 arguments` (SSLDisable.cs). I've removed 6th argument from `bool result = bnet.Init`, after this change Hooker compiled without errors.
2. When I run `Hooker path/to/Hearthstone_Data example_hooks`, I notice some "Cannot find any method..." errors (full output below):
```
Cannot find any method matching GameState.OnPowerHistory
Hooking method `System.Void bgs.BattleNet::.cctor()`
Hooking method `System.Void bgs.BattleNetCSharp::AuroraStateHandler_WaitForLogon()`
Hooking method `System.String bgs.BattleNetCSharp::GetLaunchOption(System.String,System.Boolean)`
Hooking method `System.String bgs.BattleNetCSharp::GetLaunchOption(System.String,System.Boolean,System.String)`
Cannot find any method matching Network.GetBattlePayConfigResponse
Hooking method `System.Boolean bgs.BattleNetCSharp::Init(System.Boolean,System.String,System.String,System.Int32,bgs.SslParameters)`
Hooking method `System.Void GameState::OnPowerHistory(System.Collections.Generic.List`1<Network/PowerHistory>)`
Cannot find any method matching BattleNet..cctor
Cannot find any method matching BattleNetCSharp.AuroraStateHandler_WaitForLogon
Cannot find any method matching BattleNetCSharp.GetLaunchOption
Hooking method `Network/BattlePayConfig Network::GetBattlePayConfigResponse()`
Cannot find any method matching BattleNetCSharp.Init
```
Am I doing something wrong?

Thanks for any help.

**Comment by tzurbaev** [comment]
[Stove log without crashes](https://gist.github.com/tzurbaev/ede3543885124caf6698d43bc9b4f802) (client still stuck on loading screen).

**Comment by jleclanche** [comment]
You'll probably have to wait for @djkaty to get back to get an answer.

**Comment by djkaty** [comment]
Hi @tzurbaev ! Thanks for your issue report.

1. Which version of the Hearthstone client did you use when you encountered the crashes?
2. What did you change to stop the crashes?

Regarding UnityHook, this is really out of date now and I need to update the documentation. Instead, restore the original DLLs in Hearthstone_Data\Managed and use HearthSwitcher - https://github.com/djkaty/HearthSwitcher. Build it in Debug mode and set the server host to your local stove server in the Development tab when you run the app. This is a much more convenient way of switching between stove and the official servers.

Regarding the hang on the loading screen, this is a known issue with recent commits of stove. I didn't notice it until reported because it only occurs with a fresh installation - a migrate install works normally. It is on my todo list to look into this over the next weeks (unfortunately I'm very busy right now). However if you get to the point shown in your stove log without crashes, you have more than likely done everything correctly.

As an aside, you don't need to move kettle.py from its original location. "python kettle\kettle.py" from fireplace's base folder should work fine.

Hope that helps :)

Katy.

**Comment by tzurbaev** [comment]
Hi @djkaty, thanks for response.

1. I'm using version 6.1.3.14830 (Product Version 5.3.6.15686141)
2. I did no changes in code. I just ran `install -f` / `migrate -f` several times and after some time it stopped crashing.

I've compiled HearthSwitcher, set server host to 127.0.0.1 (tried with and without 1119/11200 ports and just "localhost" only). On "Play" tab entered stove's default user credentials, but when I press "Play HS" button app freezes for 5-10 seconds and shows "The management server is currently unavailable. Please try again later" error.

I've looked into source code, commented `TryGetMetadata` call, hardcoded server host and port. After this changes client finally started but stuck on loading screen again.

Running `migrate` did nothing, client still can not process after loading screen.

> it only occurs with a fresh installation - a migrate install works normally

Is there something that I can fix by myself? 

> "python kettle\kettle.py" from fireplace's base folder should work fine.

It's not working for me:
```
J:\Work\Misc\Hearthstone\fireplace>python kettle\kettle.py
Traceback (most recent call last):
  File "kettle\kettle.py", line 12, in <module>
    from fireplace import actions, cards
ImportError: No module named 'fireplace'
```

**Comment by jleclanche** [comment]
You have to install fireplace itself (setup.py install).

Do note that I haven't actually worked on fireplace in quite a while so YMMV getting this to work well.
